### ISSUE TITLE
Komplettering Examination 3

### ISSUE THREAD

**Issue by 1dv449** [WictorKihlbaum/1DV449_wk222as#2]
Komplettera uppgiften så att kartnålarna ligger rätt på kartan.

**Comment by WictorKihlbaum** [comment]
Kartnålarna och deras tillhörande popup-fönster ligger nu på korrekt position oavsett zoom-nivå.
Värdena för 'iconAnchor' och 'popupAnchor' (Rad 108 & 109 i Traffic.js) har uppdaterats.
